# NUMPY FUNCTIONS

In [10]:
import numpy as np
np.random.random()    # generate random no. between 0-1

0.8452476403657782

In [28]:
# to generate a constant value again and again we can use the seed function and then random()

np.random.seed(10)
np.random.random()

0.771320643266746

In [ ]:
# generate a random value between 3 and 10 --> using uniform() 
np.random.uniform(3,10)

3.995190333210689

In [76]:
# if want to  get 10 random value between 3 and  100 --> we can use 10 as the length in end of uniform as parameter
np.random.uniform(3,100,10).reshape(2,5) # 10 values of 2d
np.random.uniform(3,100,10)

array([68.1119198 , 71.51409586, 85.75607508, 53.63880798, 45.94865637,
       56.7135988 , 66.2435003 , 79.48972582, 89.55013681, 32.98320039])

In [119]:
# To generate an integer value within an given range
np.random.randint(20,30)
np.random.randint(20,30,5)   # random values between 20-30 with length of array = 5
np.random.randint(20,30,15).reshape(3,5) # random values between 20-30 with length = 15 and dimesion =3

array([[27, 24, 27, 25, 22],
       [21, 23, 22, 29, 20],
       [24, 27, 22, 28, 20]])

In [ ]:
# maximum of array
arr_0_1 = ([[27, 24, 27, 25, 22],
       [21, 23, 22, 29, 20],
       [24, 27, 22, 28, 20]])
np.max(arr_0_1)         # max value 
np.min(arr_0_1)         # min value

20

# argmax() and argmin() outputs the index of the max and min value of the array respectively

In [ ]:
# if want index of the maximum value --> use argmax()
np.argmax(arr_0_1)   # 29 is the max. no. and 8 is the index of that max no. from the array

8

In [ ]:

# if pass argmax() in that array itself gives the max value as index is of max value of the array
arr_10_20 = [10, 20, 30, 40, 50]
arr_10_20[np.argmax(arr_10_20)]         

50

In [ ]:
random_arr = np.arange(0,10)
random_arr
random_arr[random_arr%2==1] = -1   # repalced all the odd values with -1
random_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [238]:
# if don't want to change the array itself after performing the operation

# where(condition,True,False) --> syntax --> provide condition if it is True what would be the value if False what would be the value
random_arr = np.arange(0,10)
np.where(random_arr%2,-1,random_arr)   # array where condition is true replaced with -1 and where is False replaced with the same no

random_arr   # this operation cannot change the original array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [256]:
# Percentile --> percentile(array_name,percentile_value)
random_arr = np.arange(0,100)
np.percentile(random_arr,99)  # output value less than 25 percentile



98.01